#!/usr/bin/env python

import requests
import json
import sys

# we simply need prepend the name value plus period to the keys
def modify_data(name,success,data):

  json_data = json.loads(data)
  json_data['success'] = int(success)

  modified_data = {}
  for (k, v) in json_data.items():
    modified_data[name + "." + k] = v

  return modified_data

# data variable optional
def notify(token,name,success,data = '{}'):

  url = "https://hub.cloudradar.io/cct/"
  # Need format like so for data: { "backup.success": 1, "backup.target" : "backup.example.com"}
  payload = modify_data(name,success,data)
  headers = { 'X-CustomCheck-Token': token }

  response = requests.request("POST", url, data=json.dumps(payload), headers=headers)
  if response.status_code != 204:
    sys.stderr.write("Sending data failed. " + response.text + "\n" )
    sys.exit(response.status_code)

# let try our first simplified example
#notify('123456','ns1dns', 0, { "target": "ns1.example.com" })

if len(sys.argv) == 4:
   notify(sys.argv[1],sys.argv[2],sys.argv[3])
   #print str(sys.argv)
elif len(sys.argv) == 5:
   notify(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
else:
  sys.stderr.write("Example: ./notify_cloudradar 'token' 'checkname' status_integer 'json_data'\n");
  sys.exit(0)
