#!/bin/bash
# ./ssl_check domain.com 2
# of 1=success | 0=failed

# temporary file to store certificate
certificate_file=$(mktemp)

# delete temporary file on exit
trap "unlink $certificate_file" EXIT

if [ "$#" -eq "2" ]; then
  website="$1"
  min_days="$2"
  host "$website" >&-
  if [ "$?" -eq "0" ]; then
    echo -n | openssl s_client -servername "$website" -connect "$website":443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $certificate_file
    certificate_size=$(stat -c "%s" $certificate_file)
    if [ "$certificate_size" -gt "1" ]; then
      date=$(openssl x509 -in $certificate_file -enddate -noout | sed "s/.*=\(.*\)/\1/")
      date_s=$(date -d "${date}" +%s)
      now_s=$(date -d now +%s)
      date_diff=$(( (date_s - now_s) / 86400 ))
      # echo "$date_diff"
      if [[ "$date_s" -gt "$now_s" && "$date_diff" -lt "$min_days" ]]; then
        # certificate is not expired
        echo 1 # ok
      else
        # certificate is expired
        echo 0 # not ok
      fi
    else
      # certificate is empty
      echo 0 # not ok
    fi
  else
    # DNS resolution failed
    echo 0
  fi
fi
